server:
  port: 8083

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: matching-engine-service
  datasource:
    url: jdbc:postgresql://localhost:5435/tjtrade_db
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: matching-engine-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.tj.common.event